/**
 * Consolidated Mock Data
 * 
 * Single source of truth for all mock data used in development/testing.
 * When contracts are deployed, replace these with real data from:
 * - useContractData() hooks
 * - Subgraph queries
 * - Backend API routes
 * 
 * This file makes it trivial to swap mock ↔ real: just update one file.
 */

// ============ Donut Explorer Data ============

export const mockAllDonuts = [
  {
    id: "0x1",
    ownerName: "Glazier Max",
    ownerAddress: "0x1234...5678",
    personality: "Energetic" as const,
    color: "Pink",
    ageInDays: 45,
    dpsEarningRate: "2.1 DONUT/sec",
    health: 92,
    generation: 1,
  },
  {
    id: "0x2",
    ownerName: "Donut Enthusiast",
    ownerAddress: "0x2345...6789",
    personality: "Friendly" as const,
    color: "Blue",
    ageInDays: 65,
    dpsEarningRate: "4.0 DONUT/sec",
    health: 75,
    generation: 2,
  },
  {
    id: "0x3",
    ownerName: "Sweet Tooth",
    ownerAddress: "0x3456...7890",
    personality: "Lazy" as const,
    color: "Purple",
    ageInDays: 8,
    dpsEarningRate: "1.2 DONUT/sec",
    health: 68,
    generation: 1,
  },
];

// ============ Breeding Partners Data ============

export const mockAvailablePartners = [
  {
    id: "0x1",
    minerAddress: "0x1234...5678",
    ownerName: "Donut Enthusiast",
    personality: "Energetic" as const,
    color: "Pink",
    generation: 1,
    ageInDays: 45,
    health: 92,
    breedingViability: 92,
    canBreed: true,
    cooldownRemaining: "Ready!",
  },
  {
    id: "0x2",
    minerAddress: "0x2345...6789",
    ownerName: "Sweet Tooth",
    personality: "Friendly" as const,
    color: "Blue",
    generation: 2,
    ageInDays: 65,
    health: 78,
    breedingViability: 78,
    canBreed: true,
    cooldownRemaining: "Ready!",
  },
  {
    id: "0x3",
    minerAddress: "0x3456...7890",
    ownerName: "Lazy Glazer",
    personality: "Lazy" as const,
    color: "Purple",
    ageInDays: 50,
    health: 68,
    breedingViability: 68,
    canBreed: false,
    cooldownRemaining: "3d 5h remaining",
    generation: 1,
  },
];

// ============ Cosmetics Shop Data ============

export const mockCosmetics = [
  // Hats
  {
    id: "hat_1",
    name: "Wizard Hat",
    emoji: "🧙‍♂️",
    category: "hats" as const,
    price: 50,
    rarity: "common" as const,
    description: "Classic wizard hat for your donut",
    owned: false,
  },
  {
    id: "hat_2",
    name: "Crown",
    emoji: "👑",
    category: "hats" as const,
    price: 150,
    rarity: "rare" as const,
    description: "Royal crown for premium donuts",
    owned: false,
  },
  {
    id: "hat_3",
    name: "Party Hat",
    emoji: "🎉",
    category: "hats" as const,
    price: 75,
    rarity: "common" as const,
    description: "Celebrate with style",
    owned: false,
  },
  // Animations
  {
    id: "anim_1",
    name: "Dab Emote",
    emoji: "🙌",
    category: "animations" as const,
    price: 100,
    rarity: "rare" as const,
    description: "Show off with a dab",
    owned: false,
  },
  {
    id: "anim_2",
    name: "Victory Dance",
    emoji: "💃",
    category: "animations" as const,
    price: 200,
    rarity: "epic" as const,
    description: "Celebrate your wins",
    owned: false,
  },
  // Themes
  {
    id: "theme_1",
    name: "Halloween",
    emoji: "🎃",
    category: "themes" as const,
    price: 200,
    rarity: "rare" as const,
    description: "Spooky donut variant",
    owned: false,
  },
  {
    id: "theme_2",
    name: "Space Explorer",
    emoji: "🚀",
    category: "themes" as const,
    price: 300,
    rarity: "epic" as const,
    description: "Futuristic donut edition",
    owned: false,
  },
  // Names
  {
    id: "name_1",
    name: "Custom Name",
    emoji: "✏️",
    category: "names" as const,
    price: 200,
    rarity: "rare" as const,
    description: "Immortalize your donut's name on-chain",
    owned: false,
  },
];

// ============ Hall of Fame Data ============

export const mockLegendaryDonuts = [
  {
    id: "0x1",
    ownerName: "Alpha Glazer",
    ownerAddress: "0x1234...5678",
    personality: "Energetic" as const,
    color: "Pink",
    totalDaysAlive: 156,
    totalEarningsDonut: "2,340",
    totalEarningsEth: "1.23",
    status: "legendary" as const,
    retiredAt: "2024-12-01",
    traits: { generation: 1, offspringCount: 3 },
  },
  {
    id: "0x2",
    ownerName: "Donut Keeper",
    ownerAddress: "0x2345...6789",
    personality: "Friendly" as const,
    color: "Blue",
    totalDaysAlive: 127,
    totalEarningsDonut: "1,890",
    totalEarningsEth: "0.98",
    status: "retired" as const,
    retiredAt: "2024-11-15",
    traits: { generation: 2, offspringCount: 1 },
  },
];

export const mockAchievements = [
  {
    id: "first_donut",
    name: "First Donut",
    emoji: "🍩",
    description: "Mint your first donut",
    hint: "Start your Donutamagotchi journey",
    unlocked: true,
    unlockedAt: "2024-11-20",
    category: "gameplay" as const,
  },
  {
    id: "newborn",
    name: "Newborn",
    emoji: "🥚",
    description: "Reach Day 0 (obvious)",
    hint: "Just mint a donut!",
    unlocked: true,
    unlockedAt: "2024-11-20",
    category: "gameplay" as const,
  },
  {
    id: "growth_spurt",
    name: "Growth Spurt",
    emoji: "🌱",
    description: "Reach Growth phase (Day 1-30)",
    hint: "Keep feeding your donut",
    unlocked: true,
    unlockedAt: "2024-11-25",
    category: "gameplay" as const,
  },
  {
    id: "prime_time",
    name: "Prime Time",
    emoji: "⭐",
    description: "Reach Prime phase (Day 30+)",
    hint: "Your donut is fully mature!",
    unlocked: true,
    unlockedAt: "2024-12-01",
    category: "gameplay" as const,
  },
  {
    id: "twilight",
    name: "Twilight Years",
    emoji: "🌙",
    description: "Reach Twilight phase (Day 90+)",
    hint: "Your donut is reaching elder status",
    unlocked: false,
    category: "gameplay" as const,
  },
  {
    id: "legendary",
    name: "Legendary",
    emoji: "⭐⭐⭐",
    description: "Keep a donut alive for 100+ days",
    hint: "Be consistent in your care!",
    unlocked: false,
    category: "gameplay" as const,
  },
  {
    id: "first_breed",
    name: "First Breeder",
    emoji: "💕",
    description: "Successfully breed your first offspring",
    hint: "Find a breeding partner and spend 1000 tokens",
    unlocked: false,
    category: "breeding" as const,
  },
  {
    id: "family_builder",
    name: "Family Builder",
    emoji: "👨‍👩‍👧‍👦",
    description: "Produce 5 offspring",
    hint: "Keep breeding!",
    unlocked: false,
    category: "breeding" as const,
  },
  {
    id: "dynasty",
    name: "Dynasty",
    emoji: "👑",
    description: "Create a family tree with 10+ members",
    hint: "Multi-generational breeding",
    unlocked: false,
    category: "breeding" as const,
  },
  {
    id: "gen_master",
    name: "Generation Master",
    emoji: "📚",
    description: "Create a donut of Generation 4+",
    hint: "Keep breeding across generations",
    unlocked: false,
    category: "breeding" as const,
  },
  {
    id: "social_butterfly",
    name: "Social Butterfly",
    emoji: "🦋",
    description: "Visit 50 different donuts",
    hint: "Explore the Donut Explorer!",
    unlocked: false,
    category: "social" as const,
  },
  {
    id: "hall_of_famer",
    name: "Hall of Famer",
    emoji: "🏛️",
    description: "Retire a donut to the sanctuary",
    hint: "Keep a donut for 90+ days and retire it",
    unlocked: false,
    category: "social" as const,
  },
  {
    id: "popular",
    name: "Popular",
    emoji: "😍",
    description: "Have 100+ views on your donut profile",
    hint: "Make your donut cool!",
    unlocked: false,
    category: "social" as const,
  },
  {
    id: "community_star",
    name: "Community Star",
    emoji: "⭐",
    description: "Rank in top 100 of any leaderboard",
    hint: "Be the best in your category",
    unlocked: false,
    category: "social" as const,
  },
  {
    id: "fashionista",
    name: "Fashionista",
    emoji: "👗",
    description: "Own 10 cosmetics",
    hint: "Shop for accessories!",
    unlocked: false,
    category: "cosmetics" as const,
  },
  {
    id: "cosmetics_collector",
    name: "Collector's Edition",
    emoji: "🎨",
    description: "Own 25 unique cosmetics",
    hint: "Full wardrobe!",
    unlocked: false,
    category: "cosmetics" as const,
  },
  {
    id: "rare_trait",
    name: "Rare Trait",
    emoji: "💎",
    description: "Own a donut with ultra-rare coloring (1 in 1000)",
    hint: "Lucky breeding!",
    unlocked: false,
    category: "cosmetics" as const,
  },
];

export const mockEarningsLeaderboard = [
  {
    rank: 1,
    ownerName: "King Glazer Pro",
    ownerAddress: "0x1234...5678",
    donutName: "Alpha Prime",
    value: "4,250 $DONUT",
    badge: "🥇",
    detail: "45 days old",
  },
  {
    rank: 2,
    ownerName: "Donut Whale",
    ownerAddress: "0x2345...6789",
    donutName: "Blue Moon",
    value: "3,890 $DONUT",
    badge: "🥈",
    detail: "38 days old",
  },
  {
    rank: 3,
    ownerName: "Sugar Rush",
    ownerAddress: "0x3456...7890",
    donutName: "Glazed Rebel",
    value: "3,120 $DONUT",
    badge: "🥉",
    detail: "32 days old",
  },
  {
    rank: 4,
    ownerName: "Sweet Tooth",
    ownerAddress: "0x4567...8901",
    donutName: "Pink Princess",
    value: "2,950 $DONUT",
    detail: "28 days old",
  },
  {
    rank: 5,
    ownerName: "Daily Grinder",
    ownerAddress: "0x5678...9012",
    donutName: "Golden Crust",
    value: "2,340 $DONUT",
    detail: "21 days old",
  },
];

export const mockAgeLeaderboard = [
  {
    rank: 1,
    ownerName: "OG Enthusiast",
    ownerAddress: "0x1111...1111",
    donutName: "Ancient One",
    value: "156 days",
    badge: "⭐",
    detail: "4,890 $DONUT earned",
  },
  {
    rank: 2,
    ownerName: "Long Timer",
    ownerAddress: "0x2222...2222",
    donutName: "Survivor",
    value: "142 days",
    badge: "🌟",
    detail: "4,120 $DONUT earned",
  },
  {
    rank: 3,
    ownerName: "Steady Eddie",
    ownerAddress: "0x3333...3333",
    donutName: "Veteran",
    value: "128 days",
    detail: "3,890 $DONUT earned",
  },
  {
    rank: 4,
    ownerName: "Patient Player",
    ownerAddress: "0x4444...4444",
    donutName: "Persister",
    value: "115 days",
    detail: "3,450 $DONUT earned",
  },
  {
    rank: 5,
    ownerName: "Committed Caretaker",
    ownerAddress: "0x5555...5555",
    donutName: "Faithful",
    value: "103 days",
    detail: "2,980 $DONUT earned",
  },
];

export const mockBloodlineLeaderboard = [
  {
    rank: 1,
    ownerName: "Breeding Master",
    ownerAddress: "0x6666...6666",
    donutName: "Dynasty",
    value: "12 offspring",
    badge: "👑",
    detail: "Gen 4, 5 legendary ancestors",
  },
  {
    rank: 2,
    ownerName: "Family Builder",
    ownerAddress: "0x7777...7777",
    donutName: "Lineage",
    value: "9 offspring",
    badge: "🌳",
    detail: "Gen 3, 3 legendary ancestors",
  },
  {
    rank: 3,
    ownerName: "Genetic Expert",
    ownerAddress: "0x8888...8888",
    donutName: "Heritage",
    value: "8 offspring",
    detail: "Gen 3, 2 legendary ancestors",
  },
  {
    rank: 4,
    ownerName: "Breeding Enthusiast",
    ownerAddress: "0x9999...9999",
    donutName: "Bloodline",
    value: "6 offspring",
    detail: "Gen 2, 1 legendary ancestor",
  },
  {
    rank: 5,
    ownerName: "New Breeder",
    ownerAddress: "0xaaaa...aaaa",
    donutName: "Legacy",
    value: "4 offspring",
    detail: "Gen 2, First generation breeder",
  },
];

export const mockAchievementsLeaderboard = [
  {
    rank: 1,
    ownerName: "Completionist",
    ownerAddress: "0xbbbb...bbbb",
    donutName: "Champion",
    value: "18 badges",
    badge: "🏅",
    detail: "All major achievements unlocked",
  },
  {
    rank: 2,
    ownerName: "Hall of Fame Star",
    ownerAddress: "0xcccc...cccc",
    donutName: "Legend",
    value: "15 badges",
    detail: "3 retired donuts + 2 legendary",
  },
  {
    rank: 3,
    ownerName: "Social Butterfly",
    ownerAddress: "0xdddd...dddd",
    donutName: "Popular",
    value: "12 badges",
    detail: "100+ pet visits, 50+ interactions",
  },
  {
    rank: 4,
    ownerName: "Cosmetics Collector",
    ownerAddress: "0xeeee...eeee",
    donutName: "Fashionista",
    value: "10 badges",
    detail: "25+ cosmetics owned",
  },
  {
    rank: 5,
    ownerName: "Daily Grinder",
    ownerAddress: "0xffff...ffff",
    donutName: "Consistent",
    value: "8 badges",
    detail: "30-day login streak",
  },
];
